# 开发环境配置
server:
  port: 8882
  context-path: /xs-boot
# 数据源配置，请修改为你项目的实际配置
spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

  datasource:
    #url: jdbc:mysql://172.17.0.2:3306/zksdb
    url: jdbc:mysql://101.132.189.9:3306/zksdb?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

    #使用druid的话 需要多配置一个属性spring.datasource.type
    type: com.alibaba.druid.pool.DruidDataSource

    # 连接池的配置信息
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      filters: stat,wall
      stat-view-servlet:
        login-username: xushuai
        login-password: xushuai

mybatis:
  mapper-locations: classpath:mapper/*.xml

swagger2:
  enable: true


#spring.datasource.driverClassNamee = com.microsoft.sqlserver.jdbc.SQLServerDriver
