# 测试环境配置
spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/zksdb
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

swagger2:
  enable: true