# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    #url: jdbc:mysql://172.17.0.2:3306/zksdb
    url: jdbc:mysql://101.132.189.9:3306/zksdb
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8881
  context-path: /xs-boot

mybatis:
  mapper-locations: classpath:mapper/*.xml

swagger2:
  enable: true

#spring.datasource.driverClassNamee = com.microsoft.sqlserver.jdbc.SQLServerDriver
